extends SceneTree

# Directed-input integration smoke, NOT a human run, win-rate sample, or a proof
# of all routes. All pickups/traffic/construction are generated by MainScene.
# The only scenario intervention is an initial 60% hull; no fuel injection,
# forced spawn, teleport, collision disabling, or synthetic pickup is used.
const MainScene = preload("res://scenes/main.tscn")
const Launcher = preload("res://tests/PlaytestLauncher.gd")
const Config = preload("res://scripts/game_config.gd")
const Run = preload("res://scripts/run_state.gd")
const CoinPickup = preload("res://scripts/coin_pickup.gd")
const DT := 1.0 / 60.0
const SESSIONS := [
	["neon_coast", "pulse_gt", 611], ["freight_harbor", "driftwing", 2026],
	["storm_ridge", "flashpoint", 9001], ["sunrise_express", "comet_rs", 611],
	["neon_coast", "tidebreaker", 2026], ["freight_harbor", "aurora_x", 9001],
	["storm_ridge", "pulse_gt", 611], ["sunrise_express", "driftwing", 2026],
	["storm_ridge", "comet_rs", 9001], ["sunrise_express", "aurora_x", 611],
]
var failures: Array[String] = []

func _init() -> void:
	call_deferred("_run")

func _run() -> void:
	root.size = Vector2i(1280, 720)
	var totals := {"fuel": 0, "repair": 0, "coins": 0, "traffic_frames": 0, "construction_frames": 0, "oracle_frames": 0, "collision_frames": 0}
	for index in range(SESSIONS.size()):
		var stats := _sample(index)
		print("DYNAMIC_PICKUP_SAMPLE ", JSON.stringify(stats))
		for key in totals:
			totals[key] += int(stats[key])
		_check(stats.fuel > 0 and stats.repair > 0 and stats.coins > 0,
			"sample %d must contact naturally spawned fuel, repairs, and coins" % (index + 1))
		_check(stats.traffic_frames > 0 and stats.construction_frames > 0,
			"sample %d must include live traffic and scheduled construction" % (index + 1))
	print("DYNAMIC_PICKUP_TOTAL samples=10 ", JSON.stringify(totals), " failures=", failures.size())
	for failure in failures: push_error(failure)
	quit(0 if failures.is_empty() else 1)

func _sample(index: int) -> Dictionary:
	var config: Array = SESSIONS[index]
	var main = MainScene.instantiate()
	root.add_child(main)
	main.set_process(false)
	Launcher.configure_main(main, {"track_id": config[0], "vehicle_id": config[1], "difficulty_index": 1, "run_seed": config[2]})
	_check(not main.persistence_enabled, "Smoke must not write career/settings")
	main.run.begin_countdown(0.0)
	main.run.phase = Run.Phase.RUNNING
	main.integrity.current = 60.0
	var stats := {"sample": index + 1, "track": config[0], "vehicle": config[1], "seed": config[2], "fuel": 0, "repair": 0, "coins": 0,
		"traffic_frames": 0, "construction_frames": 0, "oracle_frames": 0, "collision_frames": 0}
	for frame in range(60 * 60):
		if main.run.phase != Run.Phase.RUNNING: break
		_apply_directed_input(main, stats)
		var fuels: Array = main.fuel_pickups.duplicate()
		var repairs: Array = main.repair_supplies.pickups.duplicate()
		var coins: Array = main.coin_director.coins.duplicate()
		var fuel_before: float = main.run.fuel
		var hull_before: float = main.integrity.current
		var coins_before: int = main.run.coins
		var speed_before: float = main.drive.speed
		var collisions_before: int = main.run.collisions
		main._process(DT)
		if main.run.phase != Run.Phase.RUNNING: break
		_check(not main.traffic.has_vehicle_overlap(), "sample %d frame %d NPC body overlap" % [index + 1, frame])
		_check(not main.traffic.has_full_lane_wall(), "sample %d frame %d three-lane wall" % [index + 1, frame])
		if not main.traffic.vehicles.is_empty(): stats.traffic_frames += 1
		if main.traffic.lane_events.state != 0: stats.construction_frames += 1
		var fuel_contacts := _contact_count(main, fuels, main.fuel_pickups, false)
		var repair_contacts := _contact_count(main, repairs, main.repair_supplies.pickups, false)
		var coin_contacts := _contact_count(main, coins, main.coin_director.coins, true)
		stats.fuel += fuel_contacts
		stats.repair += repair_contacts
		stats.coins += coin_contacts
		_check(main.run.coins - coins_before == coin_contacts, "Coin reward must equal actual contact count")
		if main.run.collisions != collisions_before:
			# Collisions can change speed after fuel integration and hull after repair.
			# Geometric removal/coin checks still ran; skip only numeric fuel/hull oracle.
			stats.collision_frames += 1
			continue
		stats.oracle_frames += 1
		var acceleration := maxf(0.0, (float(main.drive.speed) - speed_before) / DT)
		var expected_fuel := maxf(0.0, fuel_before - main.run.fuel_drain_per_second * Run.fuel_load(main.drive.speed, main.drive.max_speed, acceleration) * DT)
		expected_fuel = minf(main.run.max_fuel, expected_fuel + main.run.last_checkpoints_crossed * Config.CHECKPOINT_FUEL_REWARD)
		expected_fuel = minf(main.run.max_fuel, expected_fuel + fuel_contacts * Config.FUEL_PICKUP_AMOUNT)
		_check(absf(main.run.fuel - expected_fuel) < 0.001, "Fuel must change only by drain, checkpoint, and geometric pickup")
		_check(absf(main.integrity.current - minf(100.0, hull_before + repair_contacts * 20.0)) < 0.001,
			"Repair must restore 20 per geometric contact, capped at 100")
	stats.seconds = main.run.elapsed_seconds
	stats.phase = main.run.phase
	stats.collisions = main.run.collisions
	stats.hull = main.integrity.current
	stats.fuel_left = main.run.fuel
	stats.spawned_routes = main.coin_director.spawned_route_count
	stats.scheduled_events = main.traffic.lane_events.events_started_count
	_release_input()
	main.free()
	return stats

func _contact_count(main, previous: Array, remaining: Array, coin: bool) -> int:
	var total := 0
	var player_y: float = main.TrackGeometry.player_y(main.get_viewport_rect().size.y)
	var lane_width := Config.ROAD_HALF_WIDTH * 2.0 / Config.ROAD_LANE_COUNT
	for pickup in previous:
		var lane_position: float = pickup.lane_position if coin else float(pickup.lane)
		var lateral_distance := absf((lane_position - 1.0) * lane_width - main.drive.lateral_position)
		var contact := lateral_distance < (52.0 if coin else 48.0) and absf(pickup.y - player_y) < (58.0 if coin else 62.0)
		var removed := not remaining.has(pickup)
		if contact:
			_check(removed, "Contacting a naturally spawned pickup must collect it")
			total += 1
		elif removed:
			var recycle_y: float = main.get_viewport_rect().size.y + (Config.COIN_RECYCLE_MARGIN if coin else 60.0)
			_check(pickup.y >= recycle_y, "A pickup must not disappear without contact or offscreen recycling")
	return total

func _apply_directed_input(main, stats: Dictionary) -> void:
	# A bounded target-chasing probe: prioritize the first repair/fuel, then the
	# nearest visible coin; a short-horizon hazard veto may override that target.
	# No search, future seed knowledge, or synthetic world placement is used.
	var target_x: float = main.drive.lateral_position
	var player_y: float = main.TrackGeometry.player_y(main.get_viewport_rect().size.y)
	var candidates: Array = []
	if stats.repair == 0 and not main.repair_supplies.pickups.is_empty():
		candidates = main.repair_supplies.pickups
	elif (stats.fuel == 0 or main.run.fuel < 40.0) and not main.fuel_pickups.is_empty():
		candidates = main.fuel_pickups
	else:
		candidates = main.coin_director.coins
	var nearest_y := -INF
	for pickup in candidates:
		if pickup.y < 0.0 or pickup.y > player_y + 30.0 or pickup.y < nearest_y: continue
		nearest_y = pickup.y
		var lane_position: float = pickup.lane_position if pickup is CoinPickup else float(pickup.lane)
		target_x = (lane_position - 1.0) * 260.0
	var best_score := INF
	var safe_target := target_x
	for candidate in [target_x, -260.0, 0.0, 260.0]:
		var candidate_lane := 1.0 + float(candidate) / 260.0
		if main.traffic.lane_events.closed_lanes().has(roundi(candidate_lane)): continue
		var blocked := false
		for npc in main.traffic.vehicles:
			var future_y: float = npc.y + (main.drive.speed - npc.cruise_speed) * Config.ROAD_SCROLL_MULTIPLIER * 1.3
			if minf(npc.y, future_y) > player_y + 105.0 or maxf(npc.y, future_y) < player_y - 105.0: continue
			if absf(candidate_lane - npc.lane_position) < 0.48 or (npc.lane_change_enabled and absf(candidate_lane - npc.target_lane) < 0.48):
				blocked = true
				break
		if blocked: continue
		var score := absf(float(candidate) - target_x) + absf(float(candidate) - main.drive.lateral_position) * 0.1
		if score < best_score:
			best_score = score
			safe_target = candidate
	target_x = safe_target
	var authority: float = main.drive.steering_speed * main.drive.speed_steering_multiplier() * main.integrity.steering_multiplier()
	var steering := clampf((target_x - main.drive.lateral_position) / maxf(1.0, authority * DT), -1.0, 1.0)
	_release_input()
	if is_inf(best_score):
		Input.action_press("brake", 1.0)
	elif main.drive.speed < main.drive.max_speed * 0.70:
		Input.action_press("accelerate", 1.0)
	if steering > 0.0: Input.action_press("steer_right", steering)
	elif steering < 0.0: Input.action_press("steer_left", -steering)

func _release_input() -> void:
	for action in ["accelerate", "brake", "steer_left", "steer_right"]:
		Input.action_release(action)

func _check(condition: bool, message: String) -> void:
	if not condition and not failures.has(message): failures.append(message)
