class_name GameConfig
extends RefCounted

# Keep first-playable balance values together so playtest feedback can change
# the driving feel without scattering numbers across scene scripts.
const ROAD_LANE_COUNT: int = 3
const ROAD_HALF_WIDTH: float = 390.0

const START_SPEED: float = 280.0
const MAX_SPEED: float = 760.0
const ACCELERATION: float = 220.0
const BRAKING: float = 420.0
const STEERING_SPEED: float = 540.0
const ROAD_SCROLL_MULTIPLIER: float = 1.15
const HUD_SPEED_SCALE: float = 0.42

const OVERDRIVE_DOUBLE_TAP_WINDOW: float = 0.28
const OVERDRIVE_DURATION_SECONDS: float = 4.50
const OVERDRIVE_RAMP_IN_SECONDS: float = 0.70
const OVERDRIVE_RAMP_OUT_SECONDS: float = 1.00
const OVERDRIVE_COOLDOWN_SECONDS: float = 1.0
const OVERDRIVE_FUEL_COST_RATIO: float = 0.15
const OVERDRIVE_SPEED_BONUS: float = 100.0 / HUD_SPEED_SCALE
const OVERDRIVE_ACCELERATION_BONUS: float = 280.0 / HUD_SPEED_SCALE

const MIN_SPAWN_DISTANCE: float = 620.0
const MIN_TRAFFIC_GAP: float = 180.0
const COLLISION_INVULNERABILITY_SECONDS: float = 1.0
const COLLISION_SPEED_PENALTY: float = 260.0
const COLLISION_LATERAL_DISTANCE: float = 50.0
const COLLISION_LONGITUDINAL_DISTANCE: float = 72.0
const NEAR_MISS_LATERAL_DISTANCE: float = 88.0
const PASS_SETTLEMENT_DISTANCE: float = 76.0
const TRAFFIC_RANDOM_SEED: int = 20260728
const TRAFFIC_SPAWN_INTERVAL: float = 0.85

const FUEL_DRAIN_PER_SECOND: float = 4.0
const FUEL_ROLLING_RESISTANCE_LOAD: float = 0.18
const FUEL_AERODYNAMIC_RESISTANCE_LOAD: float = 0.16
const FUEL_ROLLING_RESISTANCE_FULL_SPEED_RATIO: float = 0.15
const FUEL_ACCELERATION_LOAD: float = 0.50
const FUEL_PICKUP_AMOUNT: float = 24.0
const MAX_FUEL: float = 100.0
const FUEL_GRACE_SECONDS: float = 30.0
const FUEL_PICKUP_INTERVAL: float = 8.0
const FUEL_SPAWN_SAFETY_DISTANCE: float = 240.0
const COIN_SCORE: int = 20
const COIN_ROUTE_SPAWN_Y: float = -90.0
const COIN_ROUTE_INTERVAL_DISTANCE: float = 1100.0
const COIN_ROUTE_RETRY_DISTANCE: float = 180.0
const COIN_RECYCLE_MARGIN: float = 60.0
const COIN_MAX_ACTIVE: int = 24
const COIN_PICKUP_LATERAL_DISTANCE: float = 52.0
const COIN_PICKUP_LONGITUDINAL_DISTANCE: float = 58.0
const COIN_ATTRACTION_RADIUS: float = 120.0
const OVERTAKE_SCORE: int = 80
const NEAR_MISS_SCORE: int = 120
const COMBO_WINDOW_SECONDS: float = 2.5
const COMBO_MAX_MULTIPLIER: int = 3
const COMBO_EVENTS_PER_MULTIPLIER: int = 4
const SPARK_MAX_COUNT: int = 24
const RACE_CHECKPOINT_DISTANCES := [800.0, 1600.0, 2400.0]
const RACE_FINISH_DISTANCE: float = 3200.0
const CHECKPOINT_FUEL_REWARD: float = 12.0
const LANE_EVENTS_ENABLED := true
const LANE_EVENT_WARNING_SECONDS := 2.0
const LANE_EVENT_DOUBLE_WARNING_SECONDS := 3.0
const LANE_EVENT_MIN_INTERVAL_SECONDS := 6.0
const LANE_EVENT_MAX_INTERVAL_SECONDS := 10.0
const LANE_EVENT_TAPER_CONE_COUNT := 7
const LANE_EVENT_TAPER_CONE_SPACING := 72.0
const LANE_EVENT_STRAIGHT_CONE_COUNT := 5
const LANE_EVENT_CORE_GAP := 108.0
const LANE_EVENT_CORE_TRAVEL_MARGIN := 120.0
const LANE_EVENT_CORE_HALF_LANE_RATIO := 0.42
const LANE_EVENT_CONE_HIT_COOLDOWN := 0.5
const LANE_EVENT_CONE_SPEED_PENALTY_RATIO := 0.10
